# SPDX-License-Identifier: Apache-2.0

"""Integration tests: generated Markdown output must pass markdownlint-cli2."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from specmd.parse.model import Model

# ---------------------------------------------------------------------------
# Helpers (mirrors test_config.py helpers to keep this file self-contained)
# ---------------------------------------------------------------------------

FIXTURE_MODEL = Path(__file__).parent / "fixtures" / "model"
MARKDOWNLINT = "markdownlint-cli2"


def _make_model(tmp_path: Path, yaml: str = "") -> Model:
    dest = tmp_path / "model"
    shutil.copytree(FIXTURE_MODEL, dest)
    if yaml:
        (dest / "specmd.yml").write_text(yaml, encoding="utf-8")
    return Model(dest)


def _fake_cfg(**kwargs: Any) -> Any:
    return SimpleNamespace(
        autogen_header="Generated by specmd test",
        license="Community-Spec-1.0",
        all_as_dict={
            "autogen_header": "Generated by specmd test",
            "license": "Community-Spec-1.0",
        },
        **kwargs,
    )


def _markdownlint_available() -> bool:
    return shutil.which(MARKDOWNLINT) is not None


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _markdownlint_available(), reason="markdownlint-cli2 not installed")
class TestMarkdownlint:
    def _gen_mkdocs(self, tmp_path: Path) -> Path:
        from specmd.generate.mkdocs import gen_mkdocs

        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_mkdocs(m, out, _fake_cfg())
        return out

    def _gen_singlefile(self, tmp_path: Path) -> Path:
        from specmd.generate.singlefile import gen_singlefile

        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_singlefile(m, out, _fake_cfg())
        return out

    def _lint(self, out: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(  # noqa: S603
            [MARKDOWNLINT, f"{out}/**/*.md"],
            capture_output=True,
            text=True,
            check=False,
        )

    def test_mkdocs_output_passes_markdownlint(self, tmp_path: Path) -> None:
        result = self._lint(self._gen_mkdocs(tmp_path))
        assert result.returncode == 0, f"markdownlint errors:\n{result.stdout}{result.stderr}"

    def test_singlefile_output_passes_markdownlint(self, tmp_path: Path) -> None:
        result = self._lint(self._gen_singlefile(tmp_path))
        assert result.returncode == 0, f"markdownlint errors:\n{result.stdout}{result.stderr}"
