# SPDX-FileContributor: Arthit Suriyawongkul
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0

"""Integration tests for markdownlint-cli2 compatibility.

Two directions:
- generated Markdown *output* must pass markdownlint-cli2;
- authored Markdown *input* must still parse identically after an author runs
  ``markdownlint-cli2 --fix`` on it (formatting must not change the model).
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from specmd.parse.model import Model

# ---------------------------------------------------------------------------
# Helpers (mirrors test_config.py helpers to keep this file self-contained)
# ---------------------------------------------------------------------------

FIXTURE_MODEL = Path(__file__).parent / "fixtures" / "model"
FIXTURE_MODEL_LITE = Path(__file__).parent / "fixtures" / "model-lite"
MARKDOWNLINT = "markdownlint-cli2"


def _make_model(tmp_path: Path, yaml: str = "") -> Model:
    dest = tmp_path / "model"
    shutil.copytree(FIXTURE_MODEL, dest)
    if yaml:
        (dest / "specmd.yml").write_text(yaml, encoding="utf-8")
    return Model(dest)


def _fake_cfg(**kwargs: Any) -> Any:
    return SimpleNamespace(
        autogen_header="Generated by specmd test",
        license="Community-Spec-1.0",
        all_as_dict={
            "autogen_header": "Generated by specmd test",
            "license": "Community-Spec-1.0",
        },
        **kwargs,
    )


def _markdownlint_available() -> bool:
    return shutil.which(MARKDOWNLINT) is not None


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _markdownlint_available(), reason="markdownlint-cli2 not installed")
class TestMarkdownlint:
    def _gen_mkdocs(self, tmp_path: Path) -> Path:
        from specmd.generate.mkdocs import gen_mkdocs

        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_mkdocs(m, out, _fake_cfg())
        return out

    def _gen_singlefile(self, tmp_path: Path) -> Path:
        from specmd.generate.singlefile import gen_singlefile

        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_singlefile(m, out, _fake_cfg())
        return out

    def _lint(self, out: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(  # noqa: S603
            [MARKDOWNLINT, f"{out}/**/*.md"],
            capture_output=True,
            text=True,
            check=False,
        )

    def test_mkdocs_output_passes_markdownlint(self, tmp_path: Path) -> None:
        result = self._lint(self._gen_mkdocs(tmp_path))
        assert result.returncode == 0, f"markdownlint errors:\n{result.stdout}{result.stderr}"

    def test_singlefile_output_passes_markdownlint(self, tmp_path: Path) -> None:
        result = self._lint(self._gen_singlefile(tmp_path))
        assert result.returncode == 0, f"markdownlint errors:\n{result.stdout}{result.stderr}"


@pytest.mark.skipif(not _markdownlint_available(), reason="markdownlint-cli2 not installed")
@pytest.mark.parametrize("fixture", [FIXTURE_MODEL, FIXTURE_MODEL_LITE], ids=["model", "model-lite"])
class TestMarkdownlintInputRoundtrip:
    """``markdownlint-cli2 --fix`` on authored input must not change the parsed model."""

    def test_fix_preserves_rdf(self, tmp_path: Path, fixture: Path) -> None:
        from rdflib.compare import graph_diff, isomorphic

        from specmd.generate.rdf import gen_rdf_ontology

        orig = tmp_path / "orig"
        fixed = tmp_path / "fixed"
        shutil.copytree(fixture, orig)
        shutil.copytree(fixture, fixed)

        g_before = gen_rdf_ontology(Model(orig))
        # --fix returns non-zero when it applies fixes; that is expected, not a failure.
        subprocess.run(  # noqa: S603
            [MARKDOWNLINT, "--fix", "**/*.md"],
            cwd=fixed,
            capture_output=True,
            text=True,
            check=False,
        )
        g_after = gen_rdf_ontology(Model(fixed))

        if not isomorphic(g_before, g_after):
            in_before, in_after = graph_diff(g_before, g_after)[1:]
            pytest.fail(
                "markdownlint --fix changed the parsed model.\n"
                f"only before ({len(in_before)}): {list(in_before)[:5]}\n"
                f"only after ({len(in_after)}): {list(in_after)[:5]}"
            )
