# SPDX-License-Identifier: Apache-2.0

"""Tests for specmd.yml configuration loading and its effect on all generators."""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from rdflib import Namespace, URIRef
from rdflib.namespace import DCTERMS, RDFS

from specmd.generate.mkdocs import gen_mkdocs
from specmd.generate.plantuml import gen_plantuml
from specmd.generate.rdf import gen_rdf, gen_rdf_ontology
from specmd.generate.singlefile import gen_singlefile
from specmd.parse.model import Model

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

FIXTURE_MODEL = Path(__file__).parent / "fixtures" / "model"


def _make_model(tmp_path: Path, yaml: str = "") -> Model:
    """Copy the fixture model into *tmp_path* and write *yaml* as specmd.yml."""
    dest = tmp_path / "model"
    shutil.copytree(FIXTURE_MODEL, dest)
    if yaml:
        (dest / "specmd.yml").write_text(yaml, encoding="utf-8")
    return Model(dest)


def _fake_cfg(**kwargs: Any) -> Any:
    """Minimal RunParams stand-in for generators that need autogen_header / all_as_dict."""
    return SimpleNamespace(
        autogen_header="Generated by specmd test",
        license="Community-Spec-1.0",
        all_as_dict={
            "autogen_header": "Generated by specmd test",
            "license": "Community-Spec-1.0",
        },
        **kwargs,
    )


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------


class TestConfigLoading:
    def test_no_config_file_gives_empty_dict(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path)
        assert m.config == {}

    def test_empty_config_file_gives_empty_dict(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "")
        assert m.config == {}

    def test_config_file_parsed_as_dict(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "namespace-order:\n  - Core\n")
        assert isinstance(m.config, dict)
        assert "namespace-order" in m.config

    def test_unknown_keys_silently_preserved(self, tmp_path: Path) -> None:
        # Extra keys don't crash loading; they are simply ignored by generators.
        m = _make_model(tmp_path, "custom-key: some-value\n")
        assert m.config.get("custom-key") == "some-value"


# ---------------------------------------------------------------------------
# namespace-order / include-unlisted-namespaces
# (detailed behaviour tests live in test_model.py; these test the config keys)
# ---------------------------------------------------------------------------


class TestNamespaceOrderConfig:
    def test_no_key_returns_all_alphabetically(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "plantuml:\n  title: irrelevant\n")
        assert m.namespace_order() == ["Core"]

    def test_explicit_list_honoured(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "namespace-order:\n  - Core\n")
        assert m.namespace_order() == ["Core"]

    def test_empty_list_excludes_all(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "namespace-order: []\n")
        assert m.namespace_order() == []

    def test_include_unlisted_false_by_default(self, tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
        m = _make_model(tmp_path, "namespace-order: []\n")
        with caplog.at_level(logging.WARNING, logger="specmd.parse.model"):
            result = m.namespace_order()
        assert result == []
        assert "excluded" in caplog.text

    def test_include_unlisted_true_appends_remainder(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "namespace-order: []\ninclude-unlisted-namespaces: true\n")
        assert m.namespace_order() == ["Core"]

    def test_include_unlisted_true_suppresses_exclusion_warning(self, tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
        m = _make_model(tmp_path, "namespace-order: []\ninclude-unlisted-namespaces: true\n")
        with caplog.at_level(logging.WARNING, logger="specmd.parse.model"):
            m.namespace_order()
        assert "excluded" not in caplog.text

    def test_unknown_namespace_in_list_warns(self, tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
        m = _make_model(tmp_path, "namespace-order:\n  - Core\n  - Ghost\n")
        with caplog.at_level(logging.WARNING, logger="specmd.parse.model"):
            result = m.namespace_order()
        assert result == ["Core"]
        assert "Ghost" in caplog.text


# ---------------------------------------------------------------------------
# ontology block
# ---------------------------------------------------------------------------


class TestOntologyConfig:
    def _graph(self, tmp_path: Path, ontology_yaml: str):
        m = _make_model(tmp_path, f"namespace-order:\n  - Core\n{ontology_yaml}")
        g = gen_rdf_ontology(m)
        ont = URIRef(m.base_uri)
        return g, ont

    def test_default_preferred_namespace_prefix(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path)
        g = gen_rdf_ontology(m)
        prefixes = dict(g.namespaces())
        assert "spdx" in prefixes

    def test_custom_preferred_namespace_prefix(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "namespace-order:\n  - Core\nontology:\n  preferred-namespace-prefix: myns\n")
        g = gen_rdf_ontology(m)
        assert "myns" in dict(g.namespaces())

    def test_default_label(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "")
        labels = [str(o) for _, _, o in g.triples((ont, RDFS.label, None))]
        assert any("SPDX" in lbl for lbl in labels)

    def test_custom_label(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  label: My Ontology\n")
        labels = [str(o) for _, _, o in g.triples((ont, RDFS.label, None))]
        assert "My Ontology" in labels

    def test_default_title(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "")
        titles = [str(o) for _, _, o in g.triples((ont, DCTERMS.title, None))]
        assert any("SPDX" in t for t in titles)

    def test_custom_title(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  title: My Title\n")
        titles = [str(o) for _, _, o in g.triples((ont, DCTERMS.title, None))]
        assert "My Title" in titles

    def test_default_creator(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "")
        creators = [str(o) for _, _, o in g.triples((ont, DCTERMS.creator, None))]
        assert any("SPDX" in c for c in creators)

    def test_custom_creator(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  creator: Acme Corp\n")
        creators = [str(o) for _, _, o in g.triples((ont, DCTERMS.creator, None))]
        assert "Acme Corp" in creators

    def test_default_license_is_uri(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "")
        licenses = list(g.objects(ont, DCTERMS.license))
        assert any(isinstance(lic, URIRef) for lic in licenses)

    def test_custom_license(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  license: https://example.org/license\n")
        licenses = list(g.objects(ont, DCTERMS.license))
        assert URIRef("https://example.org/license") in licenses

    def test_custom_abstract(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  abstract: Short abstract.\n")
        abstracts = [str(o) for _, _, o in g.triples((ont, DCTERMS.abstract, None))]
        assert "Short abstract." in abstracts

    def test_custom_copyright(self, tmp_path: Path) -> None:
        omg_ann = Namespace("https://www.omg.org/spec/Commons/AnnotationVocabulary/")
        g, ont = self._graph(tmp_path, "ontology:\n  copyright: Copyright Acme\n")
        copyrights = [str(o) for _, _, o in g.triples((ont, omg_ann.copyright, None))]
        assert "Copyright Acme" in copyrights

    def test_custom_references(self, tmp_path: Path) -> None:
        g, ont = self._graph(tmp_path, "ontology:\n  references: https://example.org/spec\n")
        refs = list(g.objects(ont, DCTERMS.references))
        assert URIRef("https://example.org/spec") in refs


# ---------------------------------------------------------------------------
# rdf block
# ---------------------------------------------------------------------------


class TestRdfConfig:
    def _run_gen(self, tmp_path: Path, rdf_yaml: str):
        m = _make_model(tmp_path / "m", f"namespace-order:\n  - Core\n{rdf_yaml}")
        out = tmp_path / "out"
        out.mkdir()
        gen_rdf(m, out, _fake_cfg())
        return out

    def test_default_filename_stem(self, tmp_path: Path) -> None:
        out = self._run_gen(tmp_path, "")
        assert (out / "spdx-model.ttl").exists()

    def test_default_context_filename(self, tmp_path: Path) -> None:
        out = self._run_gen(tmp_path, "")
        assert (out / "spdx-context.jsonld").exists()

    def test_custom_filename(self, tmp_path: Path) -> None:
        out = self._run_gen(tmp_path, "rdf:\n  filename: my-onto\n")
        assert (out / "my-onto.ttl").exists()
        assert not (out / "spdx-model.ttl").exists()

    def test_custom_context_filename(self, tmp_path: Path) -> None:
        out = self._run_gen(tmp_path, "rdf:\n  context-filename: my-ctx\n")
        assert (out / "my-ctx.jsonld").exists()
        assert not (out / "spdx-context.jsonld").exists()

    def test_dot_file_uses_filename(self, tmp_path: Path) -> None:
        out = self._run_gen(tmp_path, "rdf:\n  filename: custom\n")
        assert (out / "custom.dot").exists()


# ---------------------------------------------------------------------------
# plantuml block
# ---------------------------------------------------------------------------


class TestPlantumlConfig:
    def _plantuml_output(self, tmp_path: Path, plantuml_yaml: str) -> str:
        m = _make_model(tmp_path / "m", f"namespace-order:\n  - Core\n{plantuml_yaml}")
        out = tmp_path / "out"
        out.mkdir()
        gen_plantuml(m, out, _fake_cfg())
        return (out / "model.plantuml").read_text()

    def test_default_title(self, tmp_path: Path) -> None:
        content = self._plantuml_output(tmp_path, "")
        assert "title SPDXv3 model" in content

    def test_custom_title(self, tmp_path: Path) -> None:
        content = self._plantuml_output(tmp_path, "plantuml:\n  title: My Diagram\n")
        assert "title My Diagram" in content
        assert "SPDXv3" not in content

    def test_default_scale(self, tmp_path: Path) -> None:
        content = self._plantuml_output(tmp_path, "")
        assert "scale 4000*4000" in content

    def test_custom_scale(self, tmp_path: Path) -> None:
        content = self._plantuml_output(tmp_path, "plantuml:\n  scale: 2000*2000\n")
        assert "scale 2000*2000" in content
        assert "4000*4000" not in content


# ---------------------------------------------------------------------------
# license key
# ---------------------------------------------------------------------------


class TestLicenseConfig:
    def test_license_from_config(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "license: Apache-2.0\n")
        assert m.spdx_license == "Apache-2.0"

    def test_license_falls_back_to_namespace_source(self, tmp_path: Path) -> None:
        # No explicit config key -- should pick up license from namespace source file.
        m = _make_model(tmp_path)
        # Fixture namespace file carries Community-Spec-1.0.
        assert m.spdx_license == "Community-Spec-1.0"

    def test_license_config_overrides_namespace_source(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path, "license: MIT\n")
        assert m.spdx_license == "MIT"

    def test_mkdocs_frontmatter_contains_license(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\nlicense: MIT\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_mkdocs(m, out, _fake_cfg())
        # Pick any generated page and confirm frontmatter has the right license.
        page = next((out / "Core" / "Classes").glob("*.md"))
        content = page.read_text()
        assert content.startswith("---\n")
        assert "SPDX-License-Identifier: Community-Spec-1.0" in content

    def test_singlefile_frontmatter_contains_license(self, tmp_path: Path) -> None:
        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\nlicense: CC0-1.0\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_singlefile(m, out, _fake_cfg())
        content = (out / "model.md").read_text()
        assert content.startswith("---\n")
        assert "SPDX-License-Identifier: CC0-1.0" in content

    def test_singlefile_no_hardcoded_community_spec(self, tmp_path: Path) -> None:
        # When config has a different license, old hardcoded string must not appear.
        m = _make_model(tmp_path / "m", "namespace-order:\n  - Core\nlicense: MIT\n")
        out = tmp_path / "out"
        out.mkdir()
        gen_singlefile(m, out, _fake_cfg())
        content = (out / "model.md").read_text()
        assert "Community-Spec-1.0" not in content
        assert "MIT" in content
