# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0

"""CLI argument parsing and ``RunParams`` configuration object."""

import argparse
import importlib.util
import logging
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace

logger = logging.getLogger(__name__)

_ALL_FORMATS = ["jsondump", "mkdocs", "plantuml", "rdf", "tex", "webpages", "singlefile"]
_FORMAT_LABELS = {
    "jsondump": "JSON dump",
    "mkdocs": "MkDocs",
    "plantuml": "PlantUML",
    "rdf": "RDF",
    "tex": "TeX",
    "webpages": "web pages",
    "singlefile": "single-file Markdown",
}


def _add_log_args(parser: argparse.ArgumentParser) -> None:
    g = parser.add_mutually_exclusive_group()
    g.add_argument("-q", "--quiet", action="store_true", help="Show only warnings and errors (WARNING level).")
    g.add_argument("-v", "--verbose", action="store_true", help="Show all debug messages (DEBUG level).")
    g.add_argument("--debug", action="store_true", help="Like --verbose; reserved for internal debugging detail.")


def _add_input_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("input_dir", metavar="INPUT_DIR", type=_check_input_path, help="Path to the model directory.")


def _add_output_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("-o", "--output", type=Path, metavar="DIR", required=True, help="Output directory.")


def _add_force_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("-f", "--force", action="store_true", help="Overwrite existing output directories.")


def _check_input_path(p: str) -> Path:
    path = Path(p)
    if not path.exists():
        raise argparse.ArgumentTypeError(f"Input directory '{path}' does not exist.")
    if not path.is_dir():
        raise argparse.ArgumentTypeError(f"Input path '{path}' is not a directory.")
    return path


def _check_input_path_or_file(p: str) -> Path:
    path = Path(p)
    if not path.exists():
        raise argparse.ArgumentTypeError(f"Input path '{path}' does not exist.")
    return path


class RunParams(SimpleNamespace):
    """Parsed runtime parameters for a specmd invocation."""

    def __init__(self, name: str) -> None:
        self.name = name
        self._ts: datetime = datetime.now(UTC)
        self._parse_args()
        if self.command == "generate":
            self._check_requirements()

    @property
    def autogen_header(self) -> str:
        """One-line header string stamped into generated files."""
        return f"Automatically generated by specmd v{self.parser_version} on {self._ts.isoformat()}"

    @property
    def parser_version(self) -> str:
        """Version string of the running specmd package."""
        return sys.modules["specmd"].__version__  # type: ignore[attr-defined]

    @property
    def all_as_dict(self) -> dict[str, str]:
        """Template globals shared across all Jinja2 templates."""
        return {"autogen_header": self.autogen_header}

    def _check_requirements(self) -> None:
        def _check_module(module_name: str, condition: str) -> None:
            if importlib.util.find_spec(module_name) is None:
                logger.error(
                    "Python module '%s' is required for %s. Make sure it's installed.",
                    module_name,
                    condition,
                )

        def _check_program(program_name: str, condition: str) -> None:
            if shutil.which(program_name) is None:
                logger.error(
                    "Program '%s' is required for %s. Make sure it's installed and in PATH.",
                    program_name,
                    condition,
                )

        if self.generate_mkdocs:
            _check_module("jinja2", "MkDocs generation")
        if self.generate_rdf:
            _check_module("rdflib", "RDF generation")
        if self.generate_tex:
            _check_program("pandoc", "TeX generation")
            _check_module("jinja2", "TeX generation")
        if self.generate_singlefile:
            _check_module("jinja2", "single-file generation")

    def _parse_args(self, opts: list[str] | None = None) -> None:
        if opts is None:
            opts = sys.argv[1:]

        parser = argparse.ArgumentParser(
            prog="specmd",
            description="SpecMD -- parse Markdown model definitions into RDF, diagrams, and docs.",
        )
        parser.add_argument("-V", "--version", action="version", version=f"%(prog)s {self.parser_version}")

        sub = parser.add_subparsers(dest="command", metavar="COMMAND")
        sub.required = True

        # ── generate ──────────────────────────────────────────────────────
        gen = sub.add_parser(
            "generate",
            aliases=["gen"],
            help="Generate output artefacts from a model directory.",
            description="Generate RDF, diagrams, and docs from a Markdown model directory.",
        )
        _add_input_arg(gen)
        _add_log_args(gen)
        _add_force_arg(gen)

        gen_out = gen.add_argument_group("output control")
        gen_out.add_argument("-o", "--output", type=Path, metavar="DIR", help="Root output directory; each format is written to DIR/FORMAT/.")
        gen_out.add_argument(
            "--formats",
            type=str,
            metavar="LIST",
            default=None,
            help=f"Comma-separated formats to generate (default: all). Available: {', '.join(_ALL_FORMATS)}.",
        )
        for _g in _ALL_FORMATS:
            gen_out.add_argument(
                f"--{_g}-dir", type=Path, metavar="DIR", help=f"Output directory for {_FORMAT_LABELS[_g]} (overrides --output)."
            )

        # ── validate ──────────────────────────────────────────────────────
        val = sub.add_parser(
            "validate",
            help="Validate a model directory or a single .md file.",
            description="Check raw YAML syntax and (for directories) fully parse the model.",
        )
        val.add_argument(
            "input_dir",
            metavar="INPUT",
            type=_check_input_path_or_file,
            help="Path to a model directory or a single .md file to validate.",
        )
        val.add_argument(
            "--strict",
            action="store_true",
            help="Exit with an error if any raw YAML issues are found (not just warnings).",
        )
        _add_log_args(val)

        # ── migrate ───────────────────────────────────────────────────────
        mig = sub.add_parser(
            "migrate",
            help="Convert spec-parser Markdown format to SpecMD format.",
            description="Migrate a model directory from spec-parser Markdown format to SpecMD format.",
        )
        _add_input_arg(mig)
        _add_output_arg(mig)
        _add_log_args(mig)
        _add_force_arg(mig)

        # ── export ────────────────────────────────────────────────────────
        exp = sub.add_parser(
            "export",
            help="Export a SpecMD model to another format.",
            description="Export a SpecMD model directory to another format.",
        )
        _add_input_arg(exp)
        _add_output_arg(exp)
        exp.add_argument(
            "--format",
            dest="export_format",
            metavar="FORMAT",
            choices=["legacy"],
            default="legacy",
            help="Target export format. 'legacy' = spec-parser Markdown format (default).",
        )
        _add_log_args(exp)
        _add_force_arg(exp)

        # ── parse ─────────────────────────────────────────────────────────
        parsed = parser.parse_args(opts)

        # Normalise alias
        self.command: str = "generate" if parsed.command == "gen" else parsed.command

        self.input_path: Path = parsed.input_dir
        self.force: bool = getattr(parsed, "force", False)
        self.quiet: bool = getattr(parsed, "quiet", False)
        self.verbose: bool = getattr(parsed, "verbose", False)
        self.debug: bool = getattr(parsed, "debug", False)

        if self.debug or self.verbose:
            logging.getLogger().setLevel(logging.DEBUG)
        elif self.quiet:
            logging.getLogger().setLevel(logging.WARNING)

        if self.command == "generate":
            self._parse_generate(parsed)
        elif self.command == "validate":
            self.no_output: bool = True
            self.strict: bool = getattr(parsed, "strict", False)
            for g in _ALL_FORMATS:
                setattr(self, "generate_" + g, False)
        elif self.command == "migrate":
            self.output_path: Path = parsed.output
        elif self.command == "export":
            self.output_path = parsed.output
            self.export_format: str = parsed.export_format

    def _parse_generate(self, parsed: argparse.Namespace) -> None:
        self.no_output = False

        # Format selection
        if parsed.formats is not None:
            requested = {f.strip() for f in parsed.formats.split(",")}
            invalid = requested - set(_ALL_FORMATS)
            if invalid:
                logger.error("Unknown format(s): %s. Available: %s", ", ".join(sorted(invalid)), ", ".join(_ALL_FORMATS))
            for g in _ALL_FORMATS:
                setattr(self, "generate_" + g, g in requested and g not in invalid)
        else:
            for g in _ALL_FORMATS:
                setattr(self, "generate_" + g, True)

        # Root output directory
        if parsed.output:
            self.output_path = parsed.output
            if self.output_path.exists() and not parsed.force:
                logger.error("Output directory '%s' already exists (use -f/--force to overwrite).", self.output_path)

        # Per-format output paths
        for g in _ALL_FORMATS:
            if not getattr(self, "generate_" + g, False):
                continue
            outpath_attr = f"output_{g}_path"
            per_dir: Path | None = getattr(parsed, f"{g}_dir", None)
            if per_dir is not None:
                setattr(self, outpath_attr, per_dir)
            elif (root_out := getattr(self, "output_path", None)) is not None:
                setattr(self, outpath_attr, root_out / g)
            else:
                logger.error("Format '%s' selected but no output directory specified (use -o/--output or --%s-dir).", _FORMAT_LABELS[g], g)
            if (p := getattr(self, outpath_attr, None)) and p.exists() and not parsed.force:
                logger.error("Output directory '%s' already exists (use -f/--force to overwrite).", p)

    def create_output_dirs(self) -> None:
        """Create (or wipe-and-recreate when ``--force``) each enabled output directory."""
        for g in _ALL_FORMATS:
            if getattr(self, "generate_" + g, False):
                p: Path = getattr(self, "output_" + g + "_path")
                if self.force and p.exists():
                    shutil.rmtree(p)
                p.mkdir(parents=True)
