# SPDX-FileCopyrightText: 2026-present Arthit Suriyawongkul
# SPDX-License-Identifier: Apache-2.0

name: Unit tests

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "pyproject.toml"
      - "**/*.py"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "pyproject.toml"
      - "**/*.py"

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.14" ]
      fail-fast: true
    env:
      MAIN_SUPPORT_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install . --group test

      - name: Run tests (w/o code coverage)
        if: ${{ matrix.python-version != env.MAIN_SUPPORT_VERSION }}
        run: |
          pytest tests/ -v --tb=short

      - name: Run tests (w/ code coverage)
        if: ${{ matrix.python-version == env.MAIN_SUPPORT_VERSION }}
        env:
          PYTHONPATH: src
        run: |
          coverage run -m pytest tests/ -v --tb=short

      - name: Upload coverage reports
        if: ${{ matrix.python-version == env.MAIN_SUPPORT_VERSION }}
        continue-on-error: true
        env:
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONIOENCODING: utf-8
        run: coveralls
